opBg : 'Tan'
numBg : '#3C3431'
modBg : 'Beige'
lblBg : '#FDF4E3'
opFg : 'white'
numFg : 'white'
modFg : 'black'
lblFg : 'black'

opDefaultBg : 'Tan'
numDefaultBg : '#3C3431'
modDefaultBg : 'Beige'
lblDefaultBg : '#FDF4E3'
opDefaultFg : 'white'
numDefaultFg : 'white'
modDefaultFg : 'black'
lblDefaultFg : 'black'
